markdown:  rdiscount
permalink: /:year/:month/:day/:title
title:     冰点
url:       http://guiquanz.github.com
exclude:   [ README.md sitemap.xml robots.txt atom.xml ]
author:    guiquanz
email:     nantangguyun@gmail.com
pygments:  true
paginate:  3
auto:      false

