markdown:  rdiscount
permalink: /:year/:month/:day/:title
title:     句读
url:       http://guiquanz.me
exclude:   [ README.md sitemap.xml robots.txt atom.xml ]
author:    guiquanz
email:     nantangguyun@gmail.com
pygments:  true
paginate:  3
auto:      false
noToc:     false
gitrepurl: http://github.com/guiquanz/guiquanz.github.com
contentsLabel: 目录



